# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- refs/tags/v*

variables:
  - name: nimVersion
    value: 0.20.2

jobs:
- job: Build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
        binaryName: spurdify-linux
      osx:
        imageName: 'macOS-latest'
        binaryName: spurdify-osx

  pool:
    vmImage: $(imageName)

  steps:
  - script: docker build . --build-arg nimVersion=$(nimVersion) -t spurdify
    displayName: 'Build docker container (Linux)'
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: |
      docker run --rm -v $(Build.SourcesDirectory):/app spurdify nimble upx
      sudo mv bin/spurdify $(binaryName)
    displayName: 'Build binary (Linux)'
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: |
      brew install nim upx
    displayName: 'Install dependencies (Mac)'
    condition: eq(variables['Agent.OS'], 'Darwin')

  - script: |
      export PATH=~/.nimble/bin:nim-$(nimVersion)/bin/:$PATH
      nimble upx
      mv bin/spurdify $(binaryName)
    displayName: 'Build binary (Mac)'
    condition: eq(variables['Agent.OS'], 'Darwin')

  - task: PublishPipelineArtifact@0
    displayName: Publish Artifact
    inputs:
      artifactName: $(binaryName)-build
      targetPath: $(System.DefaultWorkingDirectory)/$(binaryName)


- job: UpdateGithubRelease
  dependsOn: Build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

  steps:
  - task: DownloadPipelineArtifact@2
    displayName: Download Linux Artifacts
    inputs:
      artifactName: spurdify-linux-build
      targetPath: $(Build.ArtifactStagingDirectory)

  - task: DownloadPipelineArtifact@2
    displayName: Download OSX Artifacts
    inputs:
      artifactName: spurdify-osx-build
      targetPath: $(Build.ArtifactStagingDirectory)

  - task: GitHubRelease@0
    displayName: "Create GH release"
    inputs:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
      gitHubConnection: GitHubReleases
      isDraft: true
      releaseNotesFile: "RELEASENOTES.md"
      assets: $(System.ArtifactsDirectory)/spurdify-*
